### ISSUE TITLE
请问最近是否有代码改动？

### ISSUE THREAD

**Issue by William88555** [dawn0815/UniSA#2]
<img width="872" alt="微信图片_20240124190213" src="https://github.com/dawn0815/UniSA/assets/48777722/51b8bd32-5d46-496f-a8db-14030f7ed779">
是否可以帮忙看下这个报错

**Comment by dawn0815** [comment]
If you want to train the model from scratch, checkpoint_dir should be the path to the original BART model.

**Comment by lizaijing** [comment]
It seems that you want to train the model from scratch, then you just follow the settings in the run_pretrain_stage1.sh file and start training your model. There is no need to change any configuration. "checkpoint_dir" is the path to save your model, and "checkpoint" is the path to the original BART model. Note that you need to prepare your dataset before starting training.
